name: 'nightmare'
version: '3.3'
services:
  nightmare-db:
    container_name: nightmare-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    expose:
      - 5432
    ports:
      - 5432
  nightmare-kafka:
    container_name: nightmare-kafka
    image: bitnami/kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@0.0.0.0:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - 9093:9093
      - 9092:9092
    depends_on:
      - nightmare-zookeeper
  nightmare-zookeeper:
    container_name: nightmare-zookeeper
    image: bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  nightmare-auth-app:
    container_name: nightmare-auth-app
    build: 
      context: ..
      dockerfile: ./auth/Dockerfile.dev
    command: cargo watch -x "run"
    environment:
      TZ: Asia/Jakarta
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      ENVIRONMENT: local
      NAME: Nightmare
      SCHEME: http
      HOST: 0.0.0.0
      PORT: 8000
      PREFIX: /api/v1
      API_DOC: /doc
      DATABASE_URL: postgres://root:root@nightmare-db/auth
      AUTH_URL: postgres://root:root@nightmare-db/auth
    expose:
      - 8000
    ports:
      - 8000
    volumes:
      - ../common:/app/common
      - ./migration:/app/auth/migration
      - ./src:/app/auth/src
      - ./.env:/app/auth/.env
      - ./Cargo.toml:/app/auth/Cargo.toml